### ISSUE TITLE
Increase timeout default

### ISSUE THREAD

**Issue by domenkozar** [twosigma/nsncd#99]
Sometimes under heavy load, 3s timeout would trigger nsncd to restart, which takes down DNS for a little while.

Let me know if you want some more concrete numbers.

**Comment by blinsay** [comment]
A description of your workload and concrete numbers would be extremely helpful.

**Comment by leifwalsh** [comment]
@domenkozar can you describe your workload and observed behavior please? This sounds like maybe a problem with something else? 3s sounds like extremely high latency for a DNS lookup. If anything I think we should have defaulted to something lower.

**Comment by domenkozar** [comment]
There are 1000s of HTTP requests happening and completely overloading the machine, so DNS requests take a long time like everything else.

I don't quite understand why nsncd auto-restarts if DNS timeouts, what kind of failure mode it's trying to address?

**Comment by blinsay** [comment]
> I don't quite understand why nsncd auto-restarts if DNS timeouts, what kind of failure mode it's trying to address?

nsncd exits because there has been no thread available to handle an incoming request for the entire duration of the timeout, NOT because an individual DNS request times out. It restarts because at that point it assumes the system is so overloaded that something is wrong, maybe with one of the (badly behaving) nss modules it's calling out to.

I don't think I see the case for changing the default handoff timeout. Under heavy load it sounds like you want to both increase the number of ncnsd worker threads and to increase the handoff timeout. You can also try to disable DNS through nsncd with `NSNCD_IGNORE_HOSTS`.

**Comment by leifwalsh** [comment]
> There are 1000s of HTTP requests happening and completely overloading the machine, so DNS requests take a long time like everything else.

This isn't really at a level of detail we can work with (and we'd like to help if we can, we just don't know how from this information so far). Could you please share specific, precise details about your workload, real performance timings, and what kind of performance profile you're expecting to achieve instead? For example, something of the following shape would be helpful context (not necessarily exactly this, but something with real measurements):

> Our system supports a workload that averages N DNS lookup requests/second, with spikes of up to M requests/second. The DNS resolver underneath nsncd has p50, p90, and p99 latencies of X ms, Y ms, and Z ms respectively. When we have sustained load over P requests/second over Q seconds, we see nsncd drop R% of requests. 

It would also be helpful if you could try changing the settings that do exist and describe how the performance and availability changes with them. I think the tuning parameters you need probably already exist (I agree with @blinsay that you probably want to tweak worker threads and handoff timeout). I think we need a strong argument that this use case is both common and that nsncd's behavior in this scenario is unreasonable, in order to decide the defaults for these parameters should change. 

If your machine is already overloaded, I expect the right thing to do is to try to fix that (maybe add a caching resolver nearby, if DNS load is really driving the problem, or something). It sounds like nsncd is just turning a very bad experience (everything is slow) into an admittedly somewhat worse experience (some of those things fail outright), but I think you should be aiming at the problem underneath nsncd.

Also, yeah, try `NSNCD_IGNORE_HOSTS` if you can do DNS lookups from the client libc. But you probably want to improve DNS performance either way.

**Comment by leifwalsh** [comment]
just tidying issues, if you want to reopen this conversation feel free, I'm curious what's happening to your box
